### PR TITLE
Making cards look more like the originals

### PR DESCRIPTION
**Pull request by marmat**
Moving custom styling from JS to CSS.
Introducing type-specific card type CSS classes for that (`card_type_text`, `card_type_image`, possibly in the future `card_type_html`).

The style has been adjusted to correspond to the demo cards shown in
the Glass Talk at SXSW. In particular, I have:
- Slightly reduced the Card height
- Used the Ultra Light font variant
- Adjusted the padding of the date stamp
- Added a slight text shadow
- Adjusted the text font style for image cards

Here's a screenshot for comparison, the bottom ones are cropped from the SXSW slides:
Screen Shot 2013-04-05 at 6 15 12 PM

Feel free to ignore this pull request if you don't like the style updates ;-)

### CODE REVIEW

**Comment by Scarygami** [comment]
Awesome, thanks, I like it :) (I never was good when it comes to design)

I'll just change the timestamp to always have the same position, because it somehow doesn't feel right to have this element inconsistently placed across cards.

**Comment by marmat** [comment]
Yeah, I also thought it's kind of a strange design decision, but the in the demo cards the positions were definitely not the same (maybe to be a bit more out of sight when looking at pictures?).

Personally, I think having the 40px padding consistently looks completely fine as well (i.e. no custom padding in `.card_type_image > .card_date`). This seems to match the position in the "rich" cards (news etc.) more as well.

**Comment by Scarygami** [comment]
@kaktus621 it might just be that the demo "screenshots" used have been from different versions of Glass during development. Looking at the live demo where he swipes through several cards the position stays fixed for different types of cards: http://www.youtube.com/watch?v=JpWmGX55a40 between 14:00 and 15:00

**Comment by acroyogi** [comment]
nice work, Martin!
Yes, good decision on making the timestamp consistent, right aligned and
even margins R and bottom. I also think the timestamp should be the
{font-weight: 300} or 400 weight of Roboto for maximum legibility. The
final clue I can give is that depending on font-size, you want to include
some {letter-spacing: -1px;} to compress the characters a bit closer
together. Basically -1px for every 20px of character size seems about
right.  I'm attaching some cleanly rendered UX comps for grid
reference. Photoshop file available if thats helpful to you...

Greg
www.dsky9.com

On Fri, Apr 5, 2013 at 1:18 PM, Martin Matysiak notifications@github.comwrote:

> Yeah, I also thought it's kind of a strange design decision, but the in
> the demo cards the positions were definitely not the same (maybe to be a
> bit more out of sight when looking at pictures?).
> 
> Personally, I think having the 40px padding consistently looks completely
> fine as well (i.e. no custom padding in .card_type_image > .card_date).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Scarygami/mirror-api/pull/2#issuecomment-15968836
> .

## 

_-
Greg Roberts_
Design

http://www.gregroberts.com

connect: http://www.linkedin.com/in/acroyogi
email: design@gregroberts.com
call: +1 (770) 378.1121

click to auto-add all this info to your contacts:
http://www.gregroberts.com/v/Greg_Roberts.vcf

**Pull request merged**
